CREATE TABLE USER(
   USER_ID INT NOT NULL AUTO_INCREMENT,
   USER_ROLE INT NOT NULL,
   USER_PASSWORD INT NOT NULL,
   USER_NAME VARCHAR(200) NOT NULL,
   USER_PHONE VARCHAR(25) NOT NULL,
   USER_EMAIL VARCHAR(50) NOT NULL,
   USER_PHOTO BLOB,
   USER_LAST_UPDATED DATETIME  NOT NULL,	
   PRIMARY KEY ( USER_ID ),
   FOREIGN KEY (USER_ROLE) REFERENCES ROLE(ROLE_ID),
   FOREIGN KEY (USER_PASSWORD) REFERENCES PASSWORD(PASSWORD_ID)		
);

CREATE TABLE PASSWORD(
   PASSWORD_ID INT NOT NULL AUTO_INCREMENT,
   PASSWORD VARCHAR(20) NOT NULL,
   PRIMARY KEY ( PASSWORD_ID)
);

CREATE TABLE ROLE(
   ROLE_ID INT NOT NULL AUTO_INCREMENT,
   ROLE_NAME VARCHAR(200) NOT NULL,
   PRIMARY KEY ( ROLE_ID )
);

CREATE TABLE GEODATA(
   GEODATA_ID INT NOT NULL AUTO_INCREMENT,
   GEODATA_USER INT NOT NULL,
   GEODATA_TRIP INT,   
   GEODATA_LATITUDE VARCHAR(100),
   GEODATA_LONGITUDE VARCHAR(100),
   GEODATA_ALTITUDE VARCHAR(100),
   GEODATA_ACCURACY VARCHAR(100),
   GEODATA_ALT_ACCURACY VARCHAR(100),
   GEODATA_SPEED VARCHAR(100),
   GEODATA_HEADING VARCHAR(100),
   GEODATA_TIME DATETIME,   
   PRIMARY KEY (GEODATA_ID),
   FOREIGN KEY (GEODATA_USER) REFERENCES USER(USER_ID),
   FOREIGN KEY (GEODATA_TRIP) REFERENCES TRIP(TRIP_ID)
);

CREATE TABLE TRIP(
   TRIP_ID INT NOT NULL AUTO_INCREMENT,
   TRIP_NAME VARCHAR(100) NOT NULL,
   TRIP_USER INT NOT NULL,   
   PRIMARY KEY (TRIP_ID),
   FOREIGN KEY (TRIP_USER) REFERENCES USER(USER_ID)
);

Maven Create:

mvn archetype:generate -DgroupId=com.techiekernel.easylocate -DartifactId=EasyLocateUserService -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false

